services:
  dockwatch:
    image: ghcr.io/claudeailab/dockwatch
    container_name: dockwatch
    hostname: dockwatch
    restart: unless-stopped
    user: "0"
    environment:
      TZ: ${TZ}
    ports:
      - 8093:8093
    volumes:
      - ./config/dockwatch:/data
      - /var/run/docker.sock:/var/run/docker.sock  # required — gives access to Docker daemon
